//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:42:47 PM EDT 
//

package org.projecthdata.viewer.model.root;

import java.util.List;

import org.projecthdata.viewer.events.EventBus;
import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.ElementList;

import org.simpleframework.xml.Root;
import org.simpleframework.xml.core.Commit;
import org.simpleframework.xml.core.Validate;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://projecthdata.org/hdata/schemas/2009/06/core}section" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="extensionId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="requirement">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="mandatory"/>
 *             &lt;enumeration value="optional"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@Root(strict = false)
public class Section {

	private Extension extension = null;

	@ElementList(inline = true, required = false)
	protected List<Section> sections;

	@Attribute(required = true)
	protected String path;

	@Attribute
	protected String name;

	@Attribute(required = true)
	protected String extensionId;

	@Attribute(required = false)
	protected String requirement;

	public List<Section> getSections() {
		return this.sections;
	}
	

	/**
	 * Gets the value of the path property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPath() {
		return path;
	}

	/**
	 * Sets the value of the path property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */

	public void setPath(String value) {
		this.path = value;		
	}
	
	
	/**
	 * Recursively prepends this sections each child section's path.  
	 * 
	 */
	public void setChildrenPaths(){
		// prepend this section's path to each child's path
		if (sections != null) {
			for (Section section : sections) {
				section.setPath(path + "/" + section.getPath());
				section.setChildrenPaths();
			}
		}
	}
	
	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the extensionId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExtensionId() {
		return extensionId;
	}

	/**
	 * Sets the value of the extensionId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExtensionId(String value) {
		this.extensionId = value;
	}

	/**
	 * Gets the value of the requirement property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRequirement() {
		return requirement;
	}

	public Extension getExtension() {
		return extension;
	}

	public void setExtension(Extension extension) {
		this.extension = extension;
	}

	/**
	 * Sets the value of the requirement property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRequirement(String value) {
		this.requirement = value;
	}

	@Validate
	public void validate() {
		setChildrenPaths();
	}
}
